### ISSUE TITLE
Update project provisioning bot to give build entitlements for teams

### ISSUE THREAD

**Issue by yhfreeman** [bcgov/platform-services-registry#279]
**Describe the issue**
As a bot, I'd like to give build entitlements for teams so they can run yum or dnf to install enterprise packages from rhel repositories when necessary.

**Additional context**
See [this issue](https://github.com/BCDevOps/OpenShift4-Migration/issues/15) for details.

**Definition of done**
Update the provisioning pipeline with the required templates

**Comment by j-pye** [comment]
The PodInjectorSelector Zero Trust First template should add the securityContext field:
```
spec:
  options:
    image: 'aporeto/aporeto-init-waitforpu:release-3.14.5'
    imagePullPolicy: IfNotPresent
    warnOnlyTimeoutSeconds: 3
  securityContext: {}
  selector:
    matchLabels:
      zero-trust-first: 'true'
```
