### ISSUE TITLE
Namespaces no longer visible

### ISSUE THREAD

**Issue by rstens** [bcgov/platform-services-registry#878]
**Describe the issue**
I have access to quite a few namespaces but if I am logged into IDIR, OpenShift logs me in with my gov account, but I have access with my Github account. So effectively, I do not see my name spaces. I understand that this is how it should work in the future but there is still a bit of history out there. This will confusion with people.

A temporary workaround is to use a private window and login to OpenShift with your GitHub account. Then you can add the role binding for your gov account. (Provided you are an admin).

```yaml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: <user>-admin
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: <user>@gov.bc.ca
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
```

**Definition of done**
The gov binding needs to be added to all the namespaces that only have github admin bindings.
